### PR TITLE
automatically assume identity role on connection if token exists

### PR DESCRIPTION
**Pull request by achauvin-wish**
This commit backports the boto3 assume_role_with_web_identity_ funtion to our boto repository. Upon creation of a connection (such as S3, ec2 etc..) the sdk will check for the environment variable AWS_WEB_IDENTITY_TOKEN_FILE and if it exists, it will automatically assume a role using the JWT token in the file and obtain credentials before proceeding to the origin connection. The credentials assumed will also automatically be refreshed

This is a post about fine-grained roles for k8s: https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/
Each k8s pod is able to obtain a jwt token which it can use to assume role and obtain temporary credentials using the boto SDK when establishing an aws connection. However, this feature is only available in boto3, and we use a version of boto2. Therefore, although our pods have a jwt token, our sdk does not do anything with it. 
This commit backports this function so that every app in clroot using boto to access aws will automatically assume a role and obtain credentials needed

### CODE REVIEW

**Comment by optix2000** [comment]
For posterity, can we put in permalinks for where we pulled the backported files from?

**Comment by optix2000** [comment]
And why it's needed

**Comment by achauvin-wish** [comment]
> For posterity, can we put in permalinks for where we pulled the backported files from?

There is only one file which the code is backported (boto/credentials.py) and I have added the permalink referencing to the original file

**Review by jwagner-wish — APPROVED** [review]
Looks good

**Pull request merged**
